image::https://cdn.rawgit.com/decidim/decidim/develop/logo.svg[Decidim Logo,400]

The participatory democracy framework.

[NOTE]
.Support release of Decidim v0.27
====
This is a support version of Decidim v0.27 to provide continued support for newer Ruby versions in order to continue the maintenance of Decidim instances still running on that version due to a difficult upgrade path. We do not guarantee any further support for this version of Decidim, so use it with caution and your own consideration. We maintain this branch only in order to continue supporting some of our customers who have more difficult upgrade paths to newer Decidim versions and to fix some problems in this Decidim version.

To install, change the `decidim-*` gems from your Gemfile to point to this branch within this repository and run the following NPM command to install the customized NPM packages:

`npm i https://github.com/mainio/decidim/raw/refs/heads/release/0.27-stable-ruby3.4/packages-pack/decidim-core-0.27.10.tgz`

Currently all tests are passing up to Ruby 3.4. When considering using this support version, please test your instance and all relevant functionality thoroughly.

This version maintains backwards compatibility with v0.27 where it is possible with newer Ruby versions. However, there are some differences to the original v0.27 that you should be aware of.

Most significant changes compared to the original v0.27:

* The following new dependencies are added in `decidim-core` due to them being removed from the standard Ruby library:
 ** `benchmark` (to be removed in Ruby 3.5)
 ** `drb` (removed in Ruby 3.4)
 ** `irb` (to be removed in Ruby 3.5)
 ** `mutex_m` (removed in Ruby 3.4)
 ** `observer` (removed in Ruby 3.4)
 ** `rdoc` (to be removed in Ruby 3.5)
* The `pg` and `pg_search` gems have been updated to versions compatible with newer Ruby versions.
* The `webpush` gem has been replaced with `web-push` to support OpenSSLv3 and newer Ruby versions.
* `seven_zip_ruby` has been replaced with a C library `libarchive` with FFI bindings to the Ruby code.
 ** This changes the password protected ZIP files to be normal AES-256 encrypted and password protected ZIP files that have wider support for different ZIP archive software. Therefore, 7-Zip is no longer necessary to open these files but they should work fine with 7-Zip as well.
 ** You may need to run `apt install libarchive`, `apt install libarchive13`, or `apt install libarchive13t64` in case your operating system or container does not come with a pre-installed version of the shared library `libarchive`. Please adjust the commands to your operating system and the package manager in use.
 ** This change also adds dependency to the `ffi` gem in `decidim-core`. However, the `ffi` gem has been already a Decidim dependency through some other gems.
* The following method signatures have been changed (and also all calls to these methods) to make them compatible with newer Ruby versions:
 ** `Decidim::NewsletterMailer#newsletter`
 ** `Decidim::NotificationsDigestSendingDecider#must_notify?`
 ** `Decidim::Notification#daily` (an ActiveRecord scope)
 ** `Decidim::Notification#weekly` (an ActiveRecord scope)
* Ruby 3.4 compatibility fixes for the following gems:
 ** The `cells` gem's method `Cell::ViewModel#state_for_implicit_render` has been replaced with a version compatible with Ruby 3.4 in `Decidim::ViewModel`.
 ** The `graphql` gem has been updated to `1.13.x` in order to make it work with Ruby 3.4.
  *** However, the query complexity check works similarly as in older versions (see https://github.com/rmosolgo/graphql-ruby/pull/3609)
 ** The `origami` gem's class `Origami::PDF::Instruction` has been replaced with a version compatible with Ruby 3.4 within `decidim-initiatives`.
* The `decidim-bulletin_board`, `voting_schemes-dummy` and `voting_schemes-electionguard` gems have been updated to 0.24.1 to make them compatible with OpenSSLv3 and newer Ruby versions within `decidim-elections`.
====
____
Free Open-Source participatory democracy, citizen participation and open government for cities and organizations
____

https://decidim.org[Decidim] is a participatory democracy framework, written in Ruby on Rails, originally developed for the Barcelona City government online and offline participation website.
Installing these libraries will provide you a generator and gems to help you develop web applications like the ones found on <<example-applications,example applications>> or like https://try.decidim.org[our demo application].

All members of the Decidim community agree with http://www.decidim.org/contract/[Decidim Social Contract or Code of Democratic Guarantees].

'''

image:https://img.shields.io/gem/v/decidim.svg[Gem,link=https://rubygems.org/gems/decidim] image:https://img.shields.io/gem/dt/decidim.svg[Gem,link=https://rubygems.org/gems/decidim] image:https://img.shields.io/github/contributors/decidim/decidim.svg[GitHub contributors,link=https://github.com/decidim/decidim/graphs/contributors] image:http://img.shields.io/badge/yard-docs-blue.svg[Yard Docs,link=http://rubydoc.info/github/decidim/decidim/master] image:https://img.shields.io/matrix/decidimdevs:matrix.org[Matrix,link=https://matrix.to/#/#decidimdevs:matrix.org]

Code quality

image:https://codecov.io/gh/decidim/decidim/branch/develop/graph/badge.svg[codecov,link=https://codecov.io/gh/decidim/decidim] image:https://api.codeclimate.com/v1/badges/ad8fa445086e491486b6/maintainability[Maintainability,link=https://codeclimate.com/github/decidim/decidim/maintainability] image:https://d322cqt584bo4o.cloudfront.net/decidim/localized.svg[Crowdin,link=https://crowdin.com/project/decidim]

= What do you need to do?

- https://docs.decidim.org/[Official Documentation]
- <<getting-started-with-decidim,Getting started with Decidim>>
- <<how-to-contribute,Contribute to the project>>
- <<modules,Modules>>
- <<authorizations-strategies,Authorizations Strategies>>
- <<following-our-license,Following our license>>
- <<example-applications,Example applications>>
- <<security,Security>>
- <<donations,Donations>>

'''

== Getting started with Decidim

TLDR: install gem, generate a Ruby on Rails app, enjoy.

[source,console]
----
gem install decidim
decidim decidim_application
----

We've set up a guide on how to install, set up and upgrade Decidim.
See the https://docs.decidim.org/en/install/[Getting started guide].

== How to contribute

See xref:CONTRIBUTING.adoc[Contributing].

== Modules

If you need to have some features that we don't have yet, we recommend that you make a module.
This is a Ruby on Rails engine with some APIs specific to Decidim (for registering with the menus, integration with spaces like Participatory Processes or Assemblies, with /admin or /api, etc).

As a base you can use these modules, although check first that the version is compatible with your current Decidim version.
Also, you should know that until v1.0.0 We're under development, and these internal APIs can change.

We recommend that you extensively test your module.

See https://decidim.org/modules[Modules page on Decidim.org].

=== Authorizations Strategies

One specific thing regarding these kind of applications is the authorization or verification logic. This tries to solve the problem of how to verify that the user is who they say they are and that they have the right to participate in this city or organization. Read more about https://docs.decidim.org/en/customize/authorizations/[Authorizations] in our documentation.

== Following our license

If you plan to put your application in production, you'll need to publish it using the same license: GPL Affero 3.

We recommend doing that on GitHub (or any other code hosting platform) before publishing.

You can read more on "http://producingoss.com/en/governments-and-open-source.html#starting-open-for-govs[Being Open Source From Day One is Especially Important for Government Projects]".

If you have any trouble you can contact us on https://app.element.io/#/room/#decidimdevs:matrix.org[our Matrix.org chat room for developers].

== Example applications

Since Decidim is a ruby gem, you can check out the https://github.com/decidim/decidim/network/dependents?type=application[dependent repositories] to see how many applications are on the wild or tests that other developers have made. You can see a highlight of https://docs.decidim.org/en/develop/guide_example_apps/[example applications] in our documentation.

== Security

Security is very important to us.
If you have any issue regarding security, please disclose the information responsibly by sending an email to security [at] decidim [dot] org and not by creating a github/metadecidim issue.
We appreciate your effort to make Decidim more secure.
See xref:SECURITY.adoc[full security policy].

== Donations

If you want to support the project, consider making a donation through our https://opencollective.com/decidim[OpenCollective profile].
